[language-server.rust-analyzer.config]
check.allTargets = true
check.allFeatures = true
# check.targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu"]
# check.command = "clippy"
check.features = "all"
cargo.features = "all"
diagnostics.disabled = ["unresolved-proc-macro"]
